######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 24 13:56:52 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

DESTDIR = bin/

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
TRANSLATIONS += logout-it_IT.ts
RC_FILE = risorse.rc


RESOURCES += \
    resource.qrc
